import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import type { Outfit } from "../spec/index.js";
import type { Adapter, CompileResult } from "./types.js";

export const openaiAgentsAdapter: Adapter = {
  id: "openai-agents",
  title: "OpenAI Agents SDK",
  experimental: true,
  conformance: {
    routeViaGateway: true,
    denyNative: true,
    hooks: false,
    slashCommands: false,
    integrations: true,
  },

  async compile(outfit: Outfit, outfitPath: string, outDir: string): Promise<CompileResult> {
    mkdirSync(outDir, { recursive: true });
    const absOutfit = resolve(outfitPath);
    const instructions = JSON.stringify(outfit.identity.prompt);
    const model = outfit.identity.model ?? "gpt-4.1";

    const script = `// Generated by \`outfit compile --target openai-agents\`. Do not edit by hand.
import { Agent, MCPServerStdio, run } from "@openai/agents";

export async function createAgent() {
  const gateway = new MCPServerStdio({
    name: ${JSON.stringify(`outfit-${outfit.name}`)},
    command: "outfit",
    args: ["gateway", "--outfit", ${JSON.stringify(absOutfit)}],
  });
  await gateway.connect();

  return new Agent({
    name: ${JSON.stringify(outfit.name)},
    model: ${JSON.stringify(model)},
    instructions: ${instructions},
    mcpServers: [gateway],
  });
}

if (import.meta.url === \`file://\${process.argv[1]}\`) {
  const agent = await createAgent();
  const prompt = process.argv.slice(2).join(" ") || "Introduce yourself.";
  const result = await run(agent, prompt);
  console.log(result.finalOutput);
}
`;

    const outPath = join(outDir, `${outfit.name}.openai.mjs`);
    writeFileSync(outPath, script);

    return {
      files: [outPath],
      notes: [
        "Requires `@openai/agents` and the `outfit` CLI on PATH.",
        `Run with: node ${outfit.name}.openai.mjs "your prompt"`,
        "API approximate - verify against your installed @openai/agents version.",
      ],
    };
  },
};
